- name: Habilitar repositorio universe (solo Ubuntu)
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Actualizar caché de paquetes
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Instalar paquetes requeridos
  ansible.builtin.package:
    name:
      - apache2
      - php
      - php-mysql
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
      - unzip
      - wget
    state: present
  when: ansible_os_family != "RedHat"

- name: Instalar paquetes requeridos (RedHat)
  ansible.builtin.dnf:
    name:
      - httpd
      - php
      - php-mysqlnd
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-soap
      - php-intl
      - php-zip
      - unzip
      - wget
    state: present
  when: ansible_os_family == "RedHat"

- name: Crear directorio de instalación
  ansible.builtin.file:
    path: "{{ wordpress_install_dir }}"
    state: directory
    owner: "{{ wordpress_web_user }}"
    group: "{{ wordpress_web_user }}"
    mode: '0755'

- name: Descargar WordPress
  ansible.builtin.get_url:
    url: "{{ wordpress_archive_url }}"
    dest: /tmp/wordpress.tar.gz
    mode: '0644'

- name: Extraer WordPress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ wordpress_install_dir }}"
    remote_src: true
    extra_opts: [--strip-components=1]
    creates: "{{ wordpress_install_dir }}/index.php"

- name: Copiar wp-config.php desde plantilla
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ wordpress_install_dir }}/wp-config.php"
    owner: "{{ wordpress_web_user }}"
    group: "{{ wordpress_web_user }}"
    mode: '0644'

- name: Reiniciar servicio web (Debian/Ubuntu)
  ansible.builtin.service:
    name: apache2
    state: restarted
  when: ansible_os_family != "RedHat"

- name: Reiniciar servicio web (RedHat)
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"
