name: Molecule CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint molecule molecule-plugins[docker] docker

      - name: Check Docker version
        run: docker --version

      - name: Run ansible-lint
        run: ansible-lint .

      - name: Run Molecule tests step by step
        run: |
          molecule create
          molecule converge
          molecule verify
          molecule destroy
